#pragma once

/* qt core */
#include <QtCore>
#include <QObject>
#include <QString>
#include <QByteArray>
#include <QList>
#include <QVector>
#include <QMap>
#include <QHash>
#include <QSet>
#include <QPair>
#include <QSharedPointer>
#include <QScopedPointer>
#include <QPointer>
#include <QStringList>
#include <QRegularExpression>
#include <QUrl>
#include <QUuid>
#include <QDateTime>
#include <QTimer>
#include <QEventLoop>
#include <QThread>
#include <QMutex>
#include <QWaitCondition>
#include <QSemaphore>
#include <QFile>
#include <QDir>
#include <QFileInfo>
#include <QIODevice>
#include <QDataStream>
#include <QTextStream>
#include <QDebug>
#include <QLoggingCategory>
#include <QMetaObject>
#include <QVariant>
/* qt gui */
#include <QtGui>
#include <QColor>
#include <QFont>
#include <QImage>
#include <QPixmap>
#include <QBrush>
#include <QPen>
#include <QPalette>
#include <QPainter>
#include <QClipboard>
#include <QCursor>
#include <QIcon>
#include <QKeySequence>
#include <QAction>
#include <QDrag>
#include <QDropEvent>
#include <QMouseEvent>
#include <QKeyEvent>
#include <QResizeEvent>
#include <QCloseEvent>
/* qt widgets */
#include <QtWidgets>
#include <QWidget>
#include <QMainWindow>
#include <QDialog>
#include <QPushButton>
#include <QLabel>
#include <QLineEdit>
#include <QTextEdit>
#include <QPlainTextEdit>
#include <QComboBox>
#include <QListWidget>
#include <QTreeWidget>
#include <QTableWidget>
#include <QTabWidget>
#include <QStackedWidget>
#include <QSplitter>
#include <QScrollArea>
#include <QScrollBar>
#include <QSlider>
#include <QProgressBar>
#include <QStatusBar>
#include <QMenuBar>
#include <QToolBar>
#include <QMenu>
#include <QLayout>
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QGridLayout>
#include <QFormLayout>
#include <QGroupBox>
#include <QFrame>
#include <QMessageBox>
#include <QFileDialog>
#include <QColorDialog>
#include <QFontDialog>
#include <QInputDialog>
#include <QProgressDialog>
#include <QWizard>
#include <QDockWidget>
#include <QMdiArea>
#include <QMdiSubWindow>
#include <QProxyStyle>
#include <QToolBox>
#include <QCalendarWidget>
/* qt concurrent */
#include <QtConcurrent>
#include <QtConcurrentRun>
#include <QtConcurrentMap>
#include <QtConcurrentFilter>
/* stdlib */
#include <iostream>
#include <fstream>
#include <sstream>
#include <iomanip>
#include <string>
#include <string_view>
#include <vector>
#include <list>
#include <deque>
#include <forward_list>
#include <array>
#include <set>
#include <map>
#include <unordered_set>
#include <unordered_map>
#include <queue>
#include <stack>
#include <algorithm>
#include <numeric>
#include <functional>
#include <memory>
#include <utility>
#include <tuple>
#include <optional>
#include <variant>
#include <any>
#include <span>
#include <bitset>
#include <chrono>
#include <thread>
#include <mutex>
#include <condition_variable>
#include <future>
#include <atomic>
#include <filesystem>
#include <regex>
#include <random>
#include <cmath>
#include <cstdlib>
#include <cstdio>
#include <cstring>
#include <cassert>
#include <cstddef>
#include <cstdint>
#include <cstdbool>
#include <climits>
#include <cfloat>
#include <type_traits>
#include <initializer_list>
#include <iterator>
#include <exception>
#include <system_error>
#include <source_location>

/* libraries */
#include <Zydis/Zydis.h>
